# CAMO Configuration
object_detection: False
content_type:
  general:
    model: 'UCF'
    detector_config: 'ucf.yaml'  # Default model for 'general'
  face:
    model: 'UCF'
    detector_config: 'ucf_face.yaml'  # Default model for 'face'